<a href="https://colab.research.google.com/github/mrafiuddin50/Myocardial-Infarction-Complications/blob/main/mic_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/00579/MI.data

--2021-06-25 06:05:50--  https://archive.ics.uci.edu/ml/machine-learning-databases/00579/MI.data
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 452341 (442K) [application/x-httpd-php]
Saving to: ‘MI.data’

MI.data             100%[===================>] 441.74K  1.26MB/s    in 0.3s

2021-06-25 06:05:51 (1.26 MB/s) - ‘MI.data’ saved [452341/452341]

In [8]:
import pandas as pd
import numpy as np

df = pd.read_csv('MI.data',header=None)

In [9]:
df.head()

   0   1    2   3   4   5   6   7   8    ... 115 116 117 118 119 120 121 122 123
0    1  77    1   2   1   1   2   ?   3  ...   0   0   0   0   0   0   0   0   0
1    2  55    1   1   0   0   0   0   0  ...   0   0   0   0   0   0   0   0   0
2    3  52    1   0   0   0   2   ?   2  ...   0   0   0   0   0   0   0   0   0
3    4  68    0   0   0   0   2   ?   2  ...   0   0   0   0   0   1   0   0   0
4    5  60    1   0   0   0   2   ?   3  ...   0   0   0   0   0   0   0   0   0

[5 rows x 124 columns]