<a href="https://colab.research.google.com/github/mrafiuddin50/Myocardial-Infarction-Complications/blob/main/mic_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/00579/MI.data

--2021-06-23 06:17:24--  https://archive.ics.uci.edu/ml/machine-learning-databases/00579/MI.data
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 452341 (442K) [application/x-httpd-php]
Saving to: ‘MI.data’

MI.data             100%[===================>] 441.74K  1.35MB/s    in 0.3s

2021-06-23 06:17:25 (1.35 MB/s) - ‘MI.data’ saved [452341/452341]

In [ ]:
import pandas as pd

df = pd.read_csv('MI.data')

In [ ]:
df.head()

   1  77  1.1  2 1.2 1.3 2.1  ?  3  ... 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.90
0  2  55    1  1   0   0   0  0  0  ...    0    0    0    0    0    0    0    0    0
1  3  52    1  0   0   0   2  ?  2  ...    0    0    0    0    0    0    0    0    0
2  4  68    0  0   0   0   2  ?  2  ...    0    0    0    0    0    1    0    0    0
3  5  60    1  0   0   0   2  ?  3  ...    0    0    0    0    0    0    0    0    0
4  6  64    1  0   1   2   1  ?  0  ...    0    0    0    0    0    0    0    0    0

[5 rows x 124 columns]